version: '3.8'

services:
  app:
    image: archananair16/kubernet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9980:9980"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kuber
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: kuber
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: